import type { HelpEntry } from "./types";

/** Help for the marketing and content screens (Offers and Piece Sets live in offers.ts). */
export const MARKETING_HELP: HelpEntry[] = [
  {
    route: "/admin/hero-banners",
    area: "Marketing & Content",
    title: "Hero Banners",
    purpose: "The large sliding pictures at the very top of the homepage. Each banner is one slide, and a click on it takes the client to the page you choose.",
    steps: [
      "Press Add Banner, upload the artwork, write the headline and choose where it leads.",
      "Use the Status switch to show or hide a banner without deleting it.",
      "To send several banners somewhere new, change the Link dropdowns, then press the Save changes button that appears above the list.",
    ],
    sections: [
      { heading: "The list", items: [
        { term: "Order", text: "The banner's Display order. Lower numbers slide in first. Change it on the banner's edit page — the list cannot be dragged." },
        { term: "Image", text: "The desktop artwork. Click it to see it full size." },
        { term: "Title and Subtitle", text: "The Headline and Supporting text from the banner's edit page." },
        { term: "Link", text: "Where a click on the banner goes. Changes here are held until you press Save changes." },
        { term: "Status", text: "Active shows the slide on the homepage; Draft hides it but keeps everything." },
        { term: "Pencil and bin", text: "Edit the banner, or delete it for good." },
        { term: "Tick boxes, Clear and Delete selected", text: "Tick banners (or the box at the top for all), then Delete selected removes them together. Clear unticks them." },
      ] },
    ],
    notes: [
      "Deleting removes the banner and its artwork permanently. It cannot be undone — switch it to Draft if you may want it back.",
      "Slides change on their own every 5 seconds and loop round. Arrows and dots appear when there is more than one.",
      "Changes can take up to a minute to show on the website.",
      "If you upload a desktop image and then press Cancel, or replace a banner's desktop image, the unused picture turns up here as a new Active banner the next time this list opens. Check the list afterwards and delete any stray one.",
      "If a banner's desktop image is removed from the image library, the banner disappears from this list too.",
    ],
    related: [
      { label: "Homepage Layout", href: "/admin/homepage-layout" },
      { label: "Offers a banner advertises", href: "/admin/promotions" },
      { label: "Promo Banners", href: "/admin/promo-banners" },
    ],
  },
  {
    route: "/admin/hero-banners/new",
    area: "Marketing & Content",
    title: "Create a banner",
    purpose: "Add a new slide to the homepage hero. Only the desktop image and the headline are required.",
    steps: [
      "Under Banner artwork, press Choose desktop image and pick the picture. Add a Phone image too if the design has words or a wordmark.",
      "Write the Headline, and choose an answer to Where should this banner go?",
      "Leave Publish banner on to show it straight away, and set the Display order.",
      "Press Create banner.",
    ],
    sections: [
      { heading: "Banner artwork", items: [
        { term: "Desktop image", text: "Required. Around 2400 × 800 px (3:1). JPG, PNG or WebP, up to 10 MB. It is used at every size unless you add a phone image, so keep any words within the middle 70% — the edges are cropped by different amounts on different screens." },
        { term: "Phone image", text: "Optional. Around 1080 × 1080 px (square). Shown on phones and small tablets instead of the desktop image, which would otherwise lose about half its width there." },
        { term: "Replace and ✕", text: "Replace uploads a different picture; ✕ clears the slot. Nothing changes on the website until you save." },
      ] },
      { heading: "Content", items: [
        { term: "Headline", text: "Required. Names the banner in this list and is read out to clients using screen readers. It is not printed over the picture — any words the client should see must be part of the artwork." },
        { term: "Supporting text", text: "Optional. For your own reference in the list; it is not shown on the website." },
        { term: "Where should this banner go?", text: "Shop all jewellery (the default), New Arrivals, Bestsellers, Shop by Budget, any of your categories, No link, or Custom page or URL for any other page — type it as /page-name or a full web address." },
      ] },
      { heading: "Publishing and Scheduling", items: [
        { term: "Publish banner", text: "On shows the slide on the homepage; off keeps it as a draft. The badge at the top of the page shows which." },
        { term: "Display order", text: "Lower numbers come first in the slideshow. Banners with the same number sit in no fixed order." },
        { term: "Start date and End date (optional)", text: "The days the banner is meant to run." },
        { term: "Repeats on a schedule", text: "Limit the banner to Every day, On specific weekdays or On a day of the month, with optional Active from / Active until times in IST." },
      ] },
    ],
    notes: [
      "The dates and repeat schedule are saved with the banner but the homepage does not yet act on them — it shows every published banner. Switch Publish banner off yourself when a campaign ends.",
      "If you upload a desktop image and then press Cancel, that picture still appears on Hero Banners as a new published banner. Delete it there.",
      "The Create banner button stays greyed out until there is a desktop image and a headline.",
    ],
    related: [{ label: "Hero Banners", href: "/admin/hero-banners" }, { label: "Offers", href: "/admin/promotions" }],
  },
  {
    route: "/admin/hero-banners/[id]",
    area: "Marketing & Content",
    title: "Edit banner",
    purpose: "Change an existing hero slide — its artwork, headline, link, order or visibility. The fields are the same as when creating a banner.",
    steps: ["Make your changes.", "Press Save changes, or Cancel to leave without saving."],
    notes: [
      "To delete a banner, use the bin on the Hero Banners list — there is no delete button on this page.",
      "Replacing the desktop image leaves the old picture behind, and it turns up on the list as a new published banner. Delete it there after saving.",
      "Changes can take up to a minute to show on the website.",
    ],
    related: [{ label: "Hero Banners", href: "/admin/hero-banners" }],
  },
  {
    route: "/admin/auth-images",
    area: "Marketing & Content",
    title: "Login Screen Images",
    purpose: "The pictures that rotate on the left half of the sign-in and sign-up window on the website.",
    steps: ["Press Add Image and choose a picture. It joins the rotation at once.", "To take one out, press the red bin on its card and confirm."],
    sections: [
      { heading: "On this page", items: [
        { term: "Add Image", text: "Uploads one picture at a time. JPG, PNG or WebP, up to 10 MB." },
        { term: "… images in rotation", text: "How many pictures clients will see cycle on the sign-in window." },
        { term: "Image cards", text: "Each picture with its file name. The bin removes it." },
      ] },
    ],
    notes: [
      "Removing a picture deletes it permanently. To use it again, upload it again.",
      "The picture panel shows on tablets and computers only; on phones the sign-in window is the form alone.",
      "Pictures are cropped to fill a tall panel, so keep the subject near the centre.",
      "There is no way to set the order of the pictures here.",
      "Keep at least one picture in rotation so the panel is never empty.",
    ],
    related: [{ label: "Hero Banners", href: "/admin/hero-banners" }],
  },
  {
    route: "/admin/promo-banners",
    area: "Marketing & Content",
    title: "Promotional Banners",
    purpose: "Short text messages across the website: the thin scrolling strip at the very top of the pages, and the large Free Gifts band on the homepage.",
    steps: ["Press Add Banner, choose the Banner Type and write the message.", "Use the tabs to see each type; press the pencil to edit or the bin to delete."],
    sections: [
      { heading: "Tabs", items: [
        { term: "Top Scroll Messages", text: "Every active message scrolls together in one strip at the top of the homepage, shop, category, product, checkout, account and written pages. It pauses when a client points at it." },
        { term: "Free Gifts Banner", text: "A large band on the homepage. Only one shows — the active one with the lowest Display Order." },
        { term: "Special Offers", text: "Saved and listed here, but not currently shown anywhere on the website." },
      ] },
      { heading: "Columns", items: [
        { term: "Order", text: "Lower numbers come first." },
        { term: "Preview", text: "The title and message in the banner's own colours." },
        { term: "Validity", text: "The start and end dates, or Always if none are set." },
        { term: "Status", text: "Active or Inactive. Change it on the banner's edit page." },
        { term: "Pencil and bin", text: "Edit the banner, or delete it permanently after a confirmation." },
      ] },
    ],
    notes: [
      "A banner shows only while it is Active and today falls within its dates.",
      "Changes can take up to a minute to show on the website.",
      "Whether the Free Gifts band appears at all, and where, is set on Homepage Layout.",
    ],
    related: [{ label: "Homepage Layout", href: "/admin/homepage-layout" }, { label: "Offers", href: "/admin/promotions" }, { label: "Hero Banners", href: "/admin/hero-banners" }],
  },
  {
    route: "/admin/promo-banners/new",
    area: "Marketing & Content",
    title: "New Promo Banner",
    purpose: "Write a new scrolling message or Free Gifts band and choose when it runs.",
    steps: [
      "Choose the Banner Type and write the Message.",
      "Pick colours under Appearance and check the Preview.",
      "Set dates or a repeat schedule if it should only run for a while, and the Display Order.",
      "Leave Active on and press Create.",
    ],
    sections: [
      { heading: "Message", items: [
        { term: "Banner Type", text: "Top Scroll Message, Free Gifts Banner or Special Offer. See the tabs on Promotional Banners for where each appears." },
        { term: "Title", text: "Optional. On the Free Gifts band it shows as a small tag above the message. The scrolling strip shows the message only." },
        { term: "Message", text: "Required. The words clients read." },
      ] },
      { heading: "Appearance", items: [
        { term: "Background Color", text: "Pick a colour or type its code. Leave the text box empty for the house style. On the scrolling strip, the first message's background is used for the whole strip." },
        { term: "Text Color", text: "Pick a colour or type its code. Leave empty for the house style." },
        { term: "Preview", text: "Updates as you type and pick colours." },
      ] },
      { heading: "Schedule & Publishing", items: [
        { term: "Start Date and End Date (Optional)", text: "The banner shows only within these days. Leave both empty to run it with no end." },
        { term: "Repeats on a schedule", text: "Off means the banner runs the whole date window. On lets you choose Every day, On specific weekdays (tick the days under Active on) or On a day of the month." },
        { term: "Active from and Active until (optional)", text: "A time window in IST. Fill in both, or leave both empty for all day. A window may run past midnight, such as 22:00 to 02:00." },
        { term: "Display Order", text: "Lower numbers come first. Do not leave it empty — put 0 if unsure." },
        { term: "Active", text: "Off keeps the banner saved but hidden." },
      ] },
    ],
    notes: [
      "Dates change over at 5:30 am, not midnight. A banner comes down early on the morning of its End Date, so set the End Date to the day after the last full day you want it shown.",
      "The repeat schedule is honoured on product, Bestsellers, New Arrivals, checkout and account pages. The homepage, Shop all, category and written pages — and the Free Gifts band — go by the dates alone.",
      "With On specific weekdays and no days ticked, the banner never shows. Day 31 only comes round in months that have one.",
    ],
    related: [{ label: "Promo Banners", href: "/admin/promo-banners" }, { label: "Homepage Layout", href: "/admin/homepage-layout" }],
  },
  {
    route: "/admin/promo-banners/[id]",
    area: "Marketing & Content",
    title: "Edit Promo Banner",
    purpose: "Change an existing promotional message, its colours, dates or visibility. The fields are the same as for a new banner.",
    steps: ["Make your changes.", "Press Update, or Cancel to leave without saving."],
    notes: [
      "To delete a banner, use the bin on the Promotional Banners list — there is no delete button on this page.",
      "Dates change over at 5:30 am, so a banner comes down on the morning of its End Date.",
      "Changes can take up to a minute to show on the website.",
    ],
    related: [{ label: "Promo Banners", href: "/admin/promo-banners" }],
  },
  {
    route: "/admin/highlights",
    area: "Marketing & Content",
    title: "Highlights",
    purpose: "The house's own moments — expos, pop-ups, awards and press — shown as picture cards in a band on the homepage.",
    steps: ["Press Add Highlight, upload a photograph and give it a title.", "Press the pencil on a card to edit it, or the bin to delete it."],
    sections: [
      { heading: "Each card", items: [
        { term: "Picture", text: "The photograph, or the poster frame for a film. A film with no poster frame shows a film icon." },
        { term: "Badges", text: "The Kind tag, Film for a video, and Visible or Hidden." },
        { term: "Place · month and year", text: "Shown when filled in." },
        { term: "Pencil and bin", text: "Edit the highlight, or delete it." },
      ] },
    ],
    notes: [
      "Cards are listed, and shown on the homepage, by Position — lowest first, newest first where positions match.",
      "Deleting also removes its picture and poster frame permanently. To keep one for later, edit it and switch off Show on the storefront.",
      "When no highlight is visible, the band is left off the homepage entirely.",
      "The band's heading is LavIndia Highlights unless you set a Custom Title on Homepage Layout.",
      "Changes can take up to a minute to show on the website.",
    ],
    related: [{ label: "Homepage Layout", href: "/admin/homepage-layout" }, { label: "Hero Banners", href: "/admin/hero-banners" }],
  },
  {
    route: "/admin/highlights/new",
    area: "Marketing & Content",
    title: "Add a highlight",
    purpose: "Add one moment to the homepage Highlights band. Only a picture and a title are required.",
    steps: ["Press Choose image and pick a photograph or a short film.", "Write the Title, and add a description, place and date if you like.", "Leave Show on the storefront on and press Add highlight."],
    sections: [
      { heading: "Media", items: [
        { term: "Image", text: "Required. Shown as a tall card, so a portrait or square photograph works best (the frame is 4:5). Photos: JPG, PNG or WebP up to 10 MB. Films: MP4 or WebM up to 50 MB; a film plays when the client opens the card." },
        { term: "Poster frame", text: "Appears only after a film is uploaded. The still picture shown on the card before the film plays. Optional." },
      ] },
      { heading: "Details", items: [
        { term: "Title", text: "Required, e.g. IIJS Premiere 2026." },
        { term: "Description", text: "Up to 600 characters. Two lines show on the card; the rest is read when it is opened." },
        { term: "Place", text: "Where it happened, e.g. Bombay Exhibition Centre, Mumbai." },
        { term: "Date", text: "Only the month and year are shown." },
        { term: "Kind", text: "The small tag on the card. Pick Expo, Exhibition, Pop-up, Award, Press, Milestone or Collaboration, or type your own." },
        { term: "Position", text: "Lower numbers come first." },
        { term: "Link", text: "Optional. A page on your site (/story) or a full web address. Shown as Read more when the card is opened." },
        { term: "Show on the storefront", text: "Off keeps the highlight saved but hidden." },
      ] },
    ],
    notes: ["The Add highlight button stays greyed out until there is a picture and a title."],
    related: [{ label: "Highlights", href: "/admin/highlights" }],
  },
  {
    route: "/admin/highlights/[id]",
    area: "Marketing & Content",
    title: "Edit highlight",
    purpose: "Change an existing highlight. The fields are the same as when adding one.",
    steps: ["Make your changes.", "Press Save changes, or Cancel to leave without saving."],
    notes: [
      "To delete a highlight, use the bin on the Highlights list — there is no delete button on this page.",
      "Changes can take up to a minute to show on the website.",
    ],
    related: [{ label: "Highlights", href: "/admin/highlights" }],
  },
  {
    route: "/admin/homepage-layout",
    area: "Marketing & Content",
    title: "Homepage Layout",
    purpose: "Choose which bands appear on the homepage, in what order, and what some of them are called.",
    steps: ["Use the arrows, or type a number, to move a band up or down.", "Switch a band off to hide it, and type a Custom Title to rename it.", "Press Save All Changes."],
    sections: [
      { heading: "Columns", items: [
        { term: "Order", text: "The up and down arrows swap a band with its neighbour. The number box sets the position directly; lower comes first." },
        { term: "Section", text: "The band's name, what fills it, and Manage what it shows — a link to the screen where its content is changed." },
        { term: "Count badge", text: "How many items the band has right now, e.g. 4 banners. A red 0 means the band has nothing to show — add content or hide it." },
        { term: "Custom Title", text: "The heading clients see. The grey text is the default; clear the box to go back to it." },
        { term: "Visibility", text: "Visible or Hidden. Hiding a band keeps its content — switch it back on at any time." },
      ] },
      { heading: "The bands", items: [
        { term: "Hero Banner", text: "The sliding banners from Hero Banners." },
        { term: "Explore Collections", text: "Categories marked as featured, in their featured order." },
        { term: "Bestsellers", text: "Pieces ranked by units sold. Until there are orders, the newest pieces stand in and the Bestseller tag is not shown." },
        { term: "Shop Under Budget", text: "The active budget tiers." },
        { term: "Free Gifts Banner", text: "The first active Free Gifts banner from Promo Banners." },
        { term: "New Arrivals", text: "Published pieces added in the last 30 days, newest first. It fills and empties on its own." },
        { term: "Highlights", text: "Visible highlights from Highlights." },
        { term: "Trust Badges", text: "Cash on delivery, customer count, rating and support hours from Settings." },
        { term: "Coupons", text: "The “Offers for You” band: live offers switched to “Show in the storefront's offers” in Offers. Code offers show their code to copy; automatic ones say no code is needed. Private one-per-client codes never show." },
      ] },
    ],
    notes: [
      "Nothing is saved until you press Save All Changes. Leaving the page first loses your edits.",
      "Custom Title changes the heading of Explore Collections, Bestsellers, Shop Under Budget, New Arrivals, Highlights and Coupons. Hero Banner, Free Gifts Banner and Trust Badges have no heading, so a title typed there is not shown.",
      "The scrolling message strip and the menu bar always sit at the top and are not listed here.",
      "Changes, and the counts on this page, can take up to a minute to catch up with the website.",
    ],
    related: [
      { label: "Hero Banners", href: "/admin/hero-banners" },
      { label: "Promo Banners", href: "/admin/promo-banners" },
      { label: "Highlights", href: "/admin/highlights" },
      { label: "Categories", href: "/admin/categories" },
      { label: "Settings", href: "/admin/settings" },
    ],
  },
  {
    route: "/admin/content-pages",
    area: "Marketing & Content",
    title: "Page Content",
    purpose: "The written pages clients read — Contact Us, Our Story, Core Values, the FAQ and the four policies. Each comes with a ready-written draft that you can edit here.",
    steps: ["Press View to read a page as clients see it.", "Press Edit to change its words."],
    sections: [
      { heading: "Columns", items: [
        { term: "Page", text: "The page's title and its address on the website." },
        { term: "Status", text: "Shipped draft: still the original wording. Edited: your version is live. Hidden — showing draft: you have saved a version but switched it off, so clients see the original wording." },
        { term: "Sections", text: "How many headed sections the page has." },
        { term: "Last edited", text: "When someone last saved it, or Never." },
        { term: "View and Edit", text: "View opens the live page in a new tab; Edit opens the editor." },
      ] },
    ],
    notes: [
      "Pages cannot be added or removed here — only their wording changed.",
      "A saved change is live on the website straight away.",
    ],
    related: [{ label: "Settings", href: "/admin/settings" }, { label: "Audit Logs", href: "/admin/audit-logs" }],
  },
  {
    route: "/admin/content-pages/[slug]",
    area: "Marketing & Content",
    title: "Edit page content",
    purpose: "Rewrite one of the written pages. It opens on the current wording — your saved version, or the original draft if nobody has edited it yet.",
    steps: [
      "Change the Title, Intro and Last updated line as needed.",
      "Edit each section's Heading, Paragraphs and List items. Use Add section, the arrows and the bin to shape the page.",
      "Press Save changes. The page is live at once — press View page to check it.",
    ],
    sections: [
      { heading: "The page", items: [
        { term: "Title", text: "Required. The large heading at the top of the page and the name in the browser tab." },
        { term: "Last updated", text: "Typed as you want it read, e.g. 20 September 2026. Shown as Last updated … — policies should carry one; leave it empty to hide it." },
        { term: "Intro", text: "One sentence under the title. Leave empty to hide the line." },
        { term: "Use my version on the site", text: "Off shows clients the original draft instead. Your edits are kept either way; press Save changes after switching." },
      ] },
      { heading: "Each section", items: [
        { term: "Section 1 of …", text: "The arrows move the section up or down; the bin removes it. A page must keep at least one section." },
        { term: "Heading", text: "Required for every section." },
        { term: "Paragraphs", text: "Leave a blank line between paragraphs. Leave empty for a section that is only a list." },
        { term: "List items", text: "One item per line, shown as a list under the paragraphs. Leave empty for no list." },
        { term: "Add section", text: "Adds an empty section at the end." },
      ] },
    ],
    notes: [
      "Nothing is saved until you press Save changes, and leaving the page first loses your edits. There is no undo once saved.",
      "If something is missing, a list of what to fix appears under the switch and nothing is saved.",
    ],
    related: [{ label: "Page Content", href: "/admin/content-pages" }],
  },
];
