export const heroBanners = [
  {
    title: "Anti Tarnish Collection",
    subtitle: "Premium jewelry that lasts forever",
    imagePath: "/assets/pictures/herobanner/anti_tarnish_dek.jpg",
    linkUrl: "/shop",
    order: 1,
    active: true,
  },
  {
    title: "Bestseller Collection",
    subtitle: "Our most loved pieces",
    imagePath: "/assets/pictures/herobanner/bestseller-banner.jpg",
    linkUrl: "/bestsellers",
    order: 2,
    active: true,
  },
  {
    title: "Exclusive Designer Collection",
    subtitle: "Handpicked luxury pieces",
    imagePath: "/assets/pictures/herobanner/Exclusive_Banner_Desktop.jpg",
    linkUrl: "/new-arrivals",
    order: 3,
    active: true,
  },
  {
    title: "Elegant Earrings",
    subtitle: "Add sparkle to your style",
    imagePath: "/assets/pictures/herobanner/earr_desk.jpg",
    linkUrl: "/earrings",
    order: 4,
    active: true,
  },
  {
    title: "Crazy Deals",
    subtitle: "Limited time offers",
    imagePath: "/assets/pictures/herobanner/crazy_desk_extend.jpg",
    linkUrl: "/shop",
    order: 5,
    active: true,
  },
  {
    title: "Anti Tarnish Desk Collection",
    subtitle: "Premium quality guaranteed",
    imagePath: "/assets/pictures/herobanner/anti_desk.jpg",
    linkUrl: "/shop",
    order: 6,
    active: true,
  },
];
